version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/scrapers"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/scrapers"
    schedule:
      interval: "monthly"
  - package-ecosystem: "composer"
    directory: "/app"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/app"
    schedule:
      interval: "monthly"
