version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/scrapers"
    schedule:
      interval: "daily"
  - package-ecosystem: "composer"
    directory: "/app"
    schedule:
      interval: "daily"
