version: '3.7'

volumes:
  scrapers_virtualenvs: {}
  mariadb_storage: {}
  meilisearch_storage: {}

services:
  scrapers:
    build: ./scrapers
    command: poetry run flask run --host=0.0.0.0
    volumes:
      - ./scrapers:/app
      - scrapers_virtualenvs:/root/.cache/pypoetry/virtualenvs
    ports:
      - '5000:5000'
    environment:
      - FLASK_APP=ep_votes/api.py
      - FLASK_ENV=development
    stdin_open: true
    tty: true

  app:
    build: ./app
    depends_on: [scrapers, mariadb, meilisearch]
    command: php artisan serve --host 0.0.0.0
    volumes:
      - ./app:/app
    ports:
      - '8000:8000'
      - '3000:3000'
    environment:
      - APP_NAME=epvotes
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel
      - LOG_CHANNEL=stack
      - SCRAPERS_HOST=scrapers
      - SCRAPERS_PORT=5000
      - SCOUT_DRIVER=meilisearch
      - MEILISEARCH_HOST=http://meilisearch:7700
      - MEILISEARCH_PUBLIC_ENDPOINT=http://localhost:7700/
    stdin_open: true
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mariadb:
    build: ./mariadb
    volumes:
      - mariadb_storage:/var/lib/mysql
    ports:
      - '3306:3306'
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
      - MYSQL_ROOT_PASSWORD=laravel
    stdin_open: true
    tty: true
    restart: always

  meilisearch:
    image: getmeili/meilisearch
    volumes:
      - meilisearch_storage:/data.ms
    ports:
      - '7700:7700'
