version: '3.7'

volumes:
  env: {}

services:
  scrapers:
    build:
      context: ./scrapers
    volumes:
      - ./scrapers:/app
      - env:/root/.cache/pypoetry/virtualenvs
    stdin_open: true
    tty: true