version: '3.7'

volumes:
  scrapers-virtualenvs: {}

services:
  scrapers:
    build: ./scrapers
    volumes:
      - ./scrapers:/app
      - scrapers-virtualenvs:/root/.cache/pypoetry/virtualenvs
    stdin_open: true
    tty: true

  app:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - '8000:8000'
    stdin_open: true
    tty: true