---
- name: Setup PHP version
  command: "uberspace tools version use php {{ php_version }}"

- name: Setup node version
  command: "uberspace tools version use node {{ node_version }}"

- name: Check if Poetry is installed
  shell: "{{ ansible_facts.env.HOME }}/.poetry/bin/poetry --version"
  register: poetry_version
  failed_when: false

- name: Install Poetry
  when: poetry_version.rc != 0
  block:
    - name: Get Poetry installer
      get_url:
        url: "https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py"
        dest: "{{ ansible_facts.env.HOME }}/get-poetry.py"

    - name: Run Poetry installer
      command: "python{{ python_version }} {{ ansible_facts.env.HOME }}/get-poetry.py"

    - name: Remove Poetry installer
      file:
        path: "{{ ansible_facts.env.HOME }}/get-poetry.py"
        state: absent
