---
- name: Reread scrapers service
  community.general.supervisorctl:
    name: epvotes-scrapers
    state: present

- name: Restart scrapers service
  community.general.supervisorctl:
    name: epvotes-scrapers
    state: restarted
