meilisearch_displayed_attributes:
  - id
  - display_title
  - result
meilisearch_searchable_attributes:
  - display_title
  - summary
meilisearch_stop_words:
  - adopted
  - votes
  - abstentions
  - resolution
meilisearch_synonyms:
  covid:
    - corona
    - covid 19
  human:
    - humanitarian
  EU:
    - European Union
  USA:
    - United States
  UK:
    - United Kingdom
    - Great Britian
