meilisearch_index_settings:
  displayedAttributes:
    - "*"
  sortableAttributes:
    - date
  filterableAttributes:
    - members
  searchableAttributes:
    - display_title
    - summary
  stopWords:
    - adopted
    - votes
    - abstentions
    - resolution
  synonyms:
    corona:
      - covid
    human:
      - humanitarian
    EU:
      - European Union
    USA:
      - United States
    UK:
      - United Kingdom
      - Great Britian
  rankingRules:
    # This is based on the default ranking rules, the only addition being
    # that votes are by default sorted in inverse chronological order.
    # https://docs.meilisearch.com/learn/core_concepts/relevancy.html#built-in-rules
    - words
    - typo
    - proximity
    - attribute
    - sort
    - exactness
    - date:desc
