meilisearch_index_settings:
  displayedAttributes:
    - id
    - display_title
    - date
    - result
    - session_id
    - session_display_title
  searchableAttributes:
    - display_title
    - summary
  stopWords:
    - adopted
    - votes
    - abstentions
    - resolution
  synonyms:
    corona:
      - covid
    human:
      - humanitarian
    EU:
      - European Union
    USA:
      - United States
    UK:
      - United Kingdom
      - Great Britian
  rankingRules:
    - typo
    - words
    - proximity
    - attribute
    - wordsPosition
    - exactness
    - desc(date)
