[tool.poetry]
name = "ep_votes"
version = "0.1.0"
description = ""
authors = ["Till Prochaska <mail@tillprochaska.de>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.24.0"
unidecode = "^1.1.1"
flake8-black = "^0.2.1"
beautifulsoup4 = "^4.9.1"
lxml = "^4.5.2"
werkzeug = "^1.0.1"

[tool.poetry.dev-dependencies]
pytest = "^6.1.1"
flake8 = "^3.8.4"
black = "^20.8b1"
requests-mock = "^1.8.0"
mypy = "^0.790"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
