[tool.poetry]
name = "ep_votes"
version = "0.1.0"
description = ""
authors = ["Till Prochaska <mail@tillprochaska.de>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.25.1"
unidecode = "^1.2.0"
flake8-black = "^0.2.1"
beautifulsoup4 = "^4.9.3"
lxml = "^4.6.3"
werkzeug = "^1.0.1"
sentry-sdk = {extras = ["flask"], version = "^1.0.0"}
python-dotenv = "^0.17.0"
coverage = "^5.5"
pytest-cov = "^2.11.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"
flake8 = "^3.9.0"
black = "^20.8b1"
requests-mock = "^1.8.0"
mypy = "^0.812"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
