[tool.poetry]
name = "ep_votes"
version = "0.1.0"
description = ""
authors = ["Till Prochaska <mail@tillprochaska.de>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.26.0"
unidecode = "^1.3.2"
flake8-black = "^0.2.3"
beautifulsoup4 = "^4.10.0"
lxml = "^4.7.1"
werkzeug = "^2.0.2"
sentry-sdk = {extras = ["flask"], version = "^1.4.3"}
python-dotenv = "^0.19.1"
coverage = "^6.1"
pytest-cov = "^3.0.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
flake8 = "^4.0.1"
black = "^21.10b0"
requests-mock = "^1.9.3"
mypy = "^0.942"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
