---
- hosts: all
  vars_files:
    - vars/general.yml
  collections:
    - community.general
  roles:
    - setup
    - deployment
  environment:
    # Pip user packages are installed here
    PATH: "~/.local/bin:{{ ansible_env.PATH }}"
