---
- name: Update displayed attributes
  uri:
    url: "http://localhost:7700/indexes/voting_lists/settings"
    method: PATCH
    headers:
      Authorization: "Bearer {{ meilisearch_master_key }}"
    body_format: json
    body: "{{ meilisearch_index_settings }}"
    status_code: [202]
