---
- name: Check if meilisearch executable exists
  stat:
    path: "{{ ansible_facts.env.HOME }}/bin/meilisearch-{{ meilisearch_version }}"
  register: exec_stats

- name: Clone git repository
  git:
    repo: https://github.com/meilisearch/MeiliSearch
    dest: "{{ meilisearch_install_dir }}"
    version: "tags/v{{ meilisearch_version }}"
  when: not exec_stats.stat.exists

- name: Download prebuilt binary
  notify:
    - Reread meilisearch service
    - Restart meilisearch service
  get_url:
    url: "https://github.com/meilisearch/meilisearch/releases/download/v{{ meilisearch_version }}/meilisearch-linux-amd64"
    dest: "{{ ansible_facts.env.HOME }}/bin/meilisearch-{{ meilisearch_version }}"
    mode: "u+x"
  when: not exec_stats.stat.exists

- name: Copy service configuration
  notify:
    - Reread meilisearch service
    - Restart meilisearch service
  template:
    src: etc/services.d/meilisearch.ini.j2
    dest: "{{ ansible_facts.env.HOME }}/etc/services.d/meilisearch.ini"

- meta: flush_handlers

- name: Get private meilisearch keys
  uri:
    url: "http://localhost:7700/keys"
    method: GET
    headers:
      X-Meili-API-Key: "{{ meilisearch_master_key }}"
    return_content: yes
  register: keys

- name: Route traffic on subdomain to Meilisearch
  command: "uberspace web backend set {{ meilisearch_domain }} --http --port 7700"

- name: Print keys
  debug:
    msg: "{{ keys.json }}"
